[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha4"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha4"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-alpha4"
